### ISSUE TITLE
게시글/리뷰 좋아요, 싫어요 시 간혹 `잘못된 요청이거나 올바르지 않은 인증정보입니다.` 응답 받음

### ISSUE THREAD

**Issue by NCookies** [imad-project/imad-server#237]
### 재현 상황

게시글에 좋아요를 여러 번 반복하다가 싫어요 요청을 날리면 정상적으로 동작하지 않는다.

### 원인

리뷰에 좋아요/싫어요를 표시할 때 `유저 활동 기반 추천`을 위해 DB에 활동 기록을 추가 또는 삭제한다.
이 때 `user_activity` 테이블에 저장된 활동 기록이 여러 개여서 동작에 실패한다. (`query did not return a unique result`)

이러한 상황이 발생하는 근본적인 이유는 addReviewLike에서 데이터를 저장할 때 업데이트 하는게 아닌 새로 저장을 하기 때문이다.
`유저 활동 기반 추천`에서는 활동 기록 중 하나의 작품을 랜덤으로 선택하기 때문에 활동 기록 삭제 시 `removeAll`은 의미가 없다.
해당 활동 기록이 항상 **unique** 할 수 있도록 해야한다.

`UserActivityService` 클래스에서 작성된 모든 로직에 대한 검토 및 재설계가 필요할 것으로 보인다.

**Comment by NCookies** [comment]
에러 발생 시 로그

```
2024-10-29 15:42:40,948 DEBUG 757777 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Failed to complete request: org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 8
2024-10-29 15:42:40,950 ERROR 757777 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 8] with root cause

jakarta.persistence.NonUniqueResultException: query did not return a unique result: 8
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:128) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:466) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.query.sqm.internal.QuerySqmImpl.getSingleResult(QuerySqmImpl.java:1103) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:193) ~[spring-data-jpa-3.0.5.jar!/:3.0.5]
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90) ~[spring-data-jpa-3.0.5.jar!/:3.0.5]
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148) ~[spring-data-jpa-3.0.5.jar!/:3.0.5]
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136) ~[spring-data-jpa-3.0.5.jar!/:3.0.5]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.0.5.jar!/:3.0.5]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.0.5.jar!/:3.0.5]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164) ~[spring-data-commons-3.0.5.jar!/:3.0.5]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.0.5.jar!/:3.0.5]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77) ~[spring-data-commons-3.0.5.jar!/:3.0.5]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.8.jar!/:6.0.8]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.8.jar!/:6.0.8]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.8.jar!/:6.0.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.0.8.jar!/:6.0.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:134) ~[spring-data-jpa-3.0.5.jar!/:3.0.5]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223) ~[spring-aop-6.0.8.jar!/:6.0.8]
        at jdk.proxy2/jdk.proxy2.$Proxy194.findByUserAccountAndReviewAndActivityType(Unknown Source) ~[na:na]
        at com.ncookie.imad.domain.useractivity.service.UserActivityService.removeReviewLike(UserActivityService.java:92) ~[classes!/:v1.0]
```

**Comment by NCookies** [comment]
ios 클라이언트 등에서는 좋아요가 되있는 상태에서 좋아요 버튼을 누르면 `like_status: 0`으로 좋아요를 취소할 수 있었다. 이 상황에서는 기존 로직이 의도한대로 정상적으로 동작했었다.

그러나 새로운 클라이언트(@Dev-KUN-F) 구현 중 좋아요 취소 기능이 구현되지 않은 상태에서 테스트하느라 해당 문제가 발생한 것으로 보인다.

**Comment by NCookies** [comment]
클라이언트 측에 좋아요 취소 기능이 구현되어 있다면 문제가 없긴 하지만, 서버 쪽에도 안전장치를 마련해뒀다.
